### ISSUE TITLE
Problem about the calculation of 'Local model accuracy'

### ISSUE THREAD

**Issue by Sherrylife** [AIoT-MLSys-Lab/FedRolex#4]
Hi, @samiul272 . As you mentioned in your paper, _"**local model accuracy** is defined as the accuracy of the server model on each of the clients's local datasets."_ In my opinion, what you want to express is that when the total number of clients is 100 and 10 clients are randomly selected to participate in the training in each round, the calculation method of  **local model accuracy** is as follows:

1. Server sends the global model to 10 clients participating in the training;

2. Each client uses its own test dataset to evaluate the global model and gets its own **Local-Accuracy** and **Local-Loss**.

3. Average these **Local-Accuracy** values and **Local-Loss** values as the final values for this round.

However, while reading your code, I notice that your code only selects 10 fixed clients numbered 0,10,20,30,...90 to calculate **Local-accuracy** and **Local-loss** in each round (As you can see in the picture, variable `m` in you code can only take a fixed number of 10 values.), instead of selecting the test set of the current clients (their numbers are stored in the variable `user-idx` in your code) that actually participate in the training for global model evaluation. Is this really reasonable? 

![image](https://user-images.githubusercontent.com/60345931/220640356-04fe71bd-2e27-4881-89e3-d1885bb6def5.png)

On the other hand, it seems that you only use one batch of data (line 212,` result[0]`) instead of all batch of data (line 212, `result`) in the client's local test set to calculate the values of **Local-accuracy** and **Local loss** for each client, is it reasonable?

**Comment by samiul272** [comment]
If you look at the section 
```python
            for k in range(m, min(m + len(local), cfg['num_users'])):
                processes.append(local[k % len(local)]
                                 .test_model_for_user.remote(k,
                                                             [dataset_id, data_split_id, model_id, label_split_id]))
```
you will see that it selects clients 1-10 then 11 to 20 ... and calculates the accuracy of 10 clients simultaneously with ray.  `m` is the starting index of selected clients and k is the selected clients. The reason for this is that instantiating 100 clients will cause cuda memory error so we do 10 at a time. 
As for the results, I think the value actually returned by `ray.get(processes)`  is a list of lists that looks like `[[(result1, input_size), (result2, input_size)]]`. My apologies for the confusing code. Note that, in reality, we do not generally run local accuracy test in all epochs but rather until the end epoch as it takes more time than training one epoch.

**Comment by samiul272** [comment]
I see it now. You should replace the `m` in line `206` with `k`. That is a mistake on the code there. I will fix that.

**Comment by Sherrylife** [comment]
> As for the results, I think the value actually returned by ray.get(processes) is a list of lists that looks like [[(result1, input_size), (result2, input_size)]]. My apologies for the confusing code. Note that, in reality, we do not generally run local accuracy test in all epochs but rather until the end epoch as it takes more time than training one epoch.

 Hi, @samiul272 , maybe I didn't say what I meant clearly. I will show the values of `result` and` results` in the debugging process, as shown in the figure below. We can see from the figure that:

1. `results` contains the test results of 10 clients;
2. `result` contains all the batch test results of one client (in the case of 100 clients, the number of test dataset per client is 100, and since the test batch size is 50, `result` contains two batches of data).

Therefore, `result[0]` only returns the test results for the first batch of the client, which seems incorrect.

![image](https://user-images.githubusercontent.com/60345931/220803843-524450b6-6b25-430d-b1d1-cbf0379e83f1.png)

**Comment by samiul272** [comment]
Hi, `result[0]` contains the evaluation result and the size for the batch. It is a tuple having `evaluation` and `input_size`. `evaluation` is appended to the logger. We iterate over each `result` in `results` and add the `evaluation` to the logger which consequently logs that to tensorboard. Could you check the input shape of `result[0]` and `result[1]`.

**Comment by Sherrylife** [comment]
> Hi, `result[0]` contains the evaluation result and the size for the batch. It is a tuple having `evaluation` and `input_size`. `evaluation` is appended to the logger. We iterate over each `result` in `results` and add the `evaluation` to the logger which consequently logs that to tensorboard. Could you check the input shape of `result[0]` and `result[1]`.

Hi, @samiul272 . The input shape of `result[0]` and `result[1]` are as follows:

![image](https://user-images.githubusercontent.com/60345931/220834479-7571e392-f621-4bd5-aca2-ad1422b4b596.png)


As you can see, `result` contains the test results of two batches (`result[0]` and `result[1]`), each with the size of 50. The two batches together constitute the entire test dataset of this client. What I want to express is that line 212 in the code only appends the evaluation of `result[0]` to the logger, and I think both evaluations of `result[0]` and `result[1]` should be appended to the logger, because the test dataset consists of two parts, `result[0]` and `result[1]`.

**Comment by samiul272** [comment]
I see. You can use a test batch size of 100 and that should show correct behavior. I will update this bug with local accuracy too. Thanks for your diligent assessment.

**Comment by Sherrylife** [comment]
Hi, @samiul272 , my dear friend, thank you for your patient reply. I have learned a lot from your articles and codes. Thank you!

**Comment by samiul272** [comment]
I pushed the updates to append each element in the `result` variable to the logger so that the logger computes the average accuracy.
